name: game-outlet
title: GameOutlet
version: '1.0.1'
summary:  Find the best prices on PC games
# noinspection YAMLSchemaValidation
description: |
  The GameOutlet put together the latest deals in games for PC. It puts the deals for the most popular online game stores in one single place. It allows you to easily find the best deals and search for your favorite games
  
  Features
  - See the latest deals from the most popular game stores
  - Search by a game title to see its prices on these stores
base: core18
grade: stable
confinement: strict
architectures:
  - build-on: amd64
    run-on: amd64
website: https://appoutlet.github.io/
license: GPL-3.0
contact: team.appoutlet@gmail.com
donation:
  - https://ko-fi.com/appoutlet
  - https://github.com/sponsors/AppOutlet
issues: https://github.com/AppOutlet/GameOutlet/issues
source-code: https://github.com/AppOutlet/GameOutlet
type: app

apps:
  game-outlet:
    extensions:
      - gnome-3-28
    command: java -jar GameOutlet-linux-$SNAPCRAFT_TARGET_ARCH-$SNAPCRAFT_PROJECT_VERSION.jar
    plugs:
      - home
parts:
  game-outlet:
    plugin: gradle
    source: https://github.com/AppOutlet/GameOutlet.git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    gradle-version: '7.5.1'
    gradle-openjdk-version: '11'
    gradle-options: [-xtest, packageReleaseUberJarForCurrentOS]
    gradle-output-dir: build/compose/jars
    stage-packages:
      - openjdk-11-jdk
