[versions]
detekt = "1.22.0"
kotlin = "1.7.20"

[plugins]
compose = "org.jetbrains.compose:1.3.0"
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }

[libraries]
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
