[versions]
detekt = "1.22.0"
kotlin = "1.7.20"

[plugins]
commitlint = "ru.netris.commitlint:1.4.3"
compose = "org.jetbrains.compose:1.3.0"
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
gitHooks = "com.star-zero.gradle.githook:1.2.0"
kover = "org.jetbrains.kotlinx.kover:0.7.0-Alpha"
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }

[libraries]
detekt-compose = "io.nlopez.compose.rules:detekt:0.1.2"
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
truth = "com.google.truth:truth:1.1.3"
