[versions]
detekt = "1.22.0"
kotlin = "1.7.20"
kotlinx-gettext = "0.5.2"
voyager = "1.0.0-rc03"
sqldelight = "2.0.0-alpha05"
retrofit = "2.9.0"

[plugins]
commitlint = "ru.netris.commitlint:1.4.3"
compose = "org.jetbrains.compose:1.3.0"
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
gitHooks = "com.star-zero.gradle.githook:1.2.0"
kover = "org.jetbrains.kotlinx.kover:0.7.0-Alpha"
kotlinx-gettext = { id = "name.kropp.kotlinx-gettext", version.ref = "kotlinx-gettext" }
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }

[libraries]
detekt-compose = "io.nlopez.compose.rules:detekt:0.1.2"
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
koin = "io.insert-koin:koin-core:3.3.3"
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-gettext = { module = "name.kropp.kotlinx-gettext:kotlinx-gettext", version.ref = "kotlinx-gettext" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
truth = "com.google.truth:truth:1.1.3"
voyager-navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyager" }
voyager-koin = { module = "cafe.adriel.voyager:voyager-koin", version.ref = "voyager" }
voyager-transitions = { module = "cafe.adriel.voyager:voyager-transitions", version.ref = "voyager" }
sqldelight-sqliteDriver = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqldelight" }
