name: game-outlet
title: GameOutlet
version: 1.3.2
summary:  Find the best prices on PC games
# noinspection YAMLSchemaValidation
description: |
  The GameOutlet put together the latest deals in games for PC. It puts the deals for the most popular online game stores in one single place. It allows you to easily find the best deals and search for your favorite games
  
  Features
  - See the latest deals from the most popular game stores
  - Search by a game title to see its prices on these stores
base: core22
confinement: strict
architectures:
  - build-on: arm64
    build-for: arm64
  - build-on: amd64
    build-for: amd64
website: https://appoutlet.github.io/
license: GPL-3.0
contact: team.appoutlet@gmail.com
donation:
  - https://ko-fi.com/appoutlet
  - https://github.com/sponsors/AppOutlet
issues: https://github.com/AppOutlet/GameOutlet/issues
source-code: https://github.com/AppOutlet/GameOutlet
type: app
grade: stable

apps:
  game-outlet:
    command: /usr/lib/jvm/java-17-openjdk-$SNAPCRAFT_TARGET_ARCH/bin/java -jar $SNAP/GameOutlet-linux-$SNAPCRAFT_TARGET_ARCH-$SNAPCRAFT_PROJECT_VERSION.jar
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-17-openjdk-$SNAPCRAFT_TARGET_ARCH
      PATH: $JAVA_HOME/bin:$PATH
    plugs:
      - home
      - x11
      - network
      - desktop
      - desktop-legacy
      - gsettings
parts:
  game-outlet:
    plugin: nil
    source: https://github.com/AppOutlet/GameOutlet.git
    source-type: git
    source-branch: snapcraft
    build-packages:
      - ucommon-utils
      - openjdk-17-jdk
    override-build: |
      craftctl default
      ./gradlew packageReleaseUberJarForCurrentOs
    stage-packages:
      - ca-certificates-java
      - ca-certificates
      - openjdk-17-jdk
      - unzip
    override-stage: |
      craftctl default
      cp $CRAFT_PART_BUILD/build/compose/jars/GameOutlet-linux-*.jar $CRAFT_STAGE/GameOutlet-linux-$CRAFT_TARGET_ARCH-$SNAPCRAFT_PROJECT_VERSION.jar
    override-prime: |
      craftctl default
      mkdir $CRAFT_PRIME/jar
      cp $CRAFT_STAGE/GameOutlet-linux-$CRAFT_TARGET_ARCH-$SNAPCRAFT_PROJECT_VERSION.jar $CRAFT_PRIME/jar/GameOutlet-linux-$CRAFT_TARGET_ARCH-$SNAPCRAFT_PROJECT_VERSION.jar
      unzip -o $CRAFT_PRIME/jar/GameOutlet-linux-$CRAFT_TARGET_ARCH-$SNAPCRAFT_PROJECT_VERSION.jar "image/*" -d $CRAFT_PRIME/jar
      mkdir -p $HOME/.config/AppOutlet/GameOutlet/database

lint:
  ignore:
    - library:
        - usr/lib/jvm/java-17-openjdk-$CRAFT_TARGET_ARCH/*
        - usr/lib/jvm/java-11-openjdk-$CRAFT_TARGET_ARCH/*
        - usr/lib/aarch64-linux-gnu/*