name: game-outlet
title: GameOutlet
version: 1.3.2
summary:  Find the best prices on PC games
# noinspection YAMLSchemaValidation
description: |
  The GameOutlet put together the latest deals in games for PC. It puts the deals for the most popular online game stores in one single place. It allows you to easily find the best deals and search for your favorite games
  
  Features
  - See the latest deals from the most popular game stores
  - Search by a game title to see its prices on these stores
base: core18
confinement: strict
architectures:
  - build-on: arm64
    run-on: arm64
  - build-on: amd64
    run-on: amd64
website: https://appoutlet.github.io/
license: GPL-3.0
contact: team.appoutlet@gmail.com
donation:
  - https://ko-fi.com/appoutlet
  - https://github.com/sponsors/AppOutlet
issues: https://github.com/AppOutlet/GameOutlet/issues
source-code: https://github.com/AppOutlet/GameOutlet
type: app

apps:
  game-outlet:
    command: bin/java -jar jar/GameOutlet-linux-$SNAPCRAFT_TARGET_ARCH-$SNAPCRAFT_TARGET_ARCH.jar
    environment:
      PATH: $JAVA_HOME/jre/bin:$PATH
    plugs:
      - home
      - network
    extensions:
      - gnome-3-34
parts:
  game-outlet:
    plugin: gradle
    source: https://github.com/AppOutlet/GameOutlet.git
    source-type: git
    source-branch: main
    gradle-version: 7.5.1
    gradle-options: [packageReleaseUberJarForCurrentOS]
    gradle-output-dir: build/compose/jars
    override-prime: |
      snapcraftctl prime
      rm -vf usr/lib/jvm/java-11-openjdk-*/lib/security/blacklisted.certs