name: Bump version
on:
  workflow_dispatch:
    inputs:
      newVersion:
        description: 'New version (optional, defaults to next minor version)'
        required: false

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Initialize mandatory git config
        run: |
          git config user.name "AppOutlet team"
          git config user.email team.appoutlet@gmail.com
      - name: Give execution permission to semver
        run: chmod +x script/semver
      - name: Give execution permission to the script
        run: chmod +x script/bump-version.sh
      - name: Bump application version
        run: script/bump-version.sh ${{ github.event.inputs.newVersion }}
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
