name: Release
on: workflow_dispatch
jobs:
  jar:
    name: Jar release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: packageReleaseUberJarForCurrentOS
          cache-read-only: false

      - name: Set version variable
        run: |
          VER=v$(cat .version)
          echo "VERSION=$VER" >> $GITHUB_ENV

      - name: Deploy to releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/compose/jars/GameOutlet-*.jar
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
          fail_on_unmatched_files: true

  linux:
    name: Linux release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: packageReleaseDistributionForCurrentOS
          cache-read-only: false

      - name: Set version variable
        run: |
          VER=v$(cat .version)
          echo "VERSION=$VER" >> $GITHUB_ENV

      - name: Deploy to releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/compose/binaries/main-release/deb/game-outlet_*.deb
            build/compose/binaries/main-release/rpm/game-outlet-*.rpm
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
          fail_on_unmatched_files: true

  windows:
    name: Windows release
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: packageReleaseDistributionForCurrentOS
          cache-read-only: false

      - name: Set version variable
        run: |
          $VER = "v" + (Get-Content .version)
          echo "VERSION=$VER" >> $env:GITHUB_ENV

      - name: Deploy to releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/compose/binaries/main-release/exe/GameOutlet-*.exe
            build/compose/binaries/main-release/msi/GameOutlet-*.msi
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
          fail_on_unmatched_files: true

  macos:
    name: MacOS release
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: packageReleaseDistributionForCurrentOS
          cache-read-only: false

      - name: Set version variable
        run: |
          VER=v$(cat .version)
          echo "VERSION=$VER" >> $GITHUB_ENV

      - name: Deploy to releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/compose/binaries/main-release/dmg/GameOutlet-*.dmg
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
          fail_on_unmatched_files: true
